name: Sync to Google Calendar

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'  # Runs daily at 8 AM PDT

jobs:
  add-event:
    runs-on: ubuntu-latest
    env:
      GCAL_CLIENT_ID: ${{ secrets.GCAL_CLIENT_ID }}
      GCAL_CLIENT_SECRET: ${{ secrets.GCAL_CLIENT_SECRET }}
      GCAL_REDIRECT_URI: ${{ secrets.GCAL_REDIRECT_URI }}
      GCAL_REFRESH_TOKEN: ${{ secrets.GCAL_REFRESH_TOKEN }}
      GCAL_CALENDAR_ID: ${{ secrets.GCAL_CALENDAR_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Run calendar sync
        run: python3 sync_calendar.py
